### ISSUE TITLE
Update to work with current eslint-plugin-react

### ISSUE THREAD

**Issue by elbotho** [ory/eslint-config-ory-am-react#1]
```
npm WARN eslint-config-ory-am-react@2.0.0 requires a peer of eslint-plugin-react@>= 4.2.0 < 5 but none was installed.
```

current `eslint-plugin-react` version is `5.2.2`

**Comment by inyono** [comment]
Thanks for reporting this issue, @elbotho. Will probably do this today or tomorrow. If you use NPM 3 (i.e. at least Node v4), it should work anyway (with warnings).

**Comment by elbotho** [comment]
sure, wouldn't have, but you said you wanted to do it anyway :)
